tableName: lineitem
primaryKey: l_orderkey+l_linenumber
selector: type="lineitem"
timeQuantumType: YMD
timeQuantumField: l_commitdate
attributes:
- fieldName: l_orderkey
  sourceName: /data/l_orderkey
  mappingStrategy: ParentRelation
  foreignKey: orders
  type: Integer
  sourceOrdinal: 1
- fieldName: l_partkey
  sourceName: /data/l_partkey
  mappingStrategy: ParentRelation
  type: Integer
  foreignKey: part
  sourceOrdinal: 2
- fieldName: l_suppkey
  sourceName: /data/l_suppkey
  mappingStrategy: ParentRelation
  type: Integer
  foreignKey: supplier
  sourceOrdinal: 3
- fieldName: l_linenumber
  sourceName: /data/l_linenumber
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 4
- fieldName: l_quantity
  sourceName: /data/l_quantity
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 5
- fieldName: l_extendedprice
  sourceName: /data/l_extendedprice
  mappingStrategy: FloatScaleBSI
  type: Float
  scale: 2
  sourceOrdinal: 6
- fieldName: l_discount
  sourceName: /data/l_discount
  mappingStrategy: FloatScaleBSI
  type: Float
  scale: 2
  sourceOrdinal: 7
- fieldName: l_tax
  sourceName: /data/l_tax
  mappingStrategy: FloatScaleBSI
  type: Float
  scale: 2
  sourceOrdinal: 8
- fieldName: l_returnflag
  sourceName: /data/l_returnflag
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 9
- fieldName: l_linestatus
  sourceName: /data/l_linestatus
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 10
- fieldName: l_shipdate
  sourceName: /data/l_shipdate
  mappingStrategy: SysMillisBSI
  type: DateTime
  sourceOrdinal: 11
- fieldName: l_commitdate
  sourceName: /data/l_commitdate
  mappingStrategy: SysMillisBSI
  type: DateTime
  sourceOrdinal: 12
- fieldName: l_receiptdate
  sourceName: /data/l_receiptdate
  mappingStrategy: SysMillisBSI
  type: DateTime
  sourceOrdinal: 13
- fieldName: l_shipinstruct
  sourceName: /data/l_shipinstruct
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 14
- fieldName: l_shipmode
  sourceName: /data/l_shipmode
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 15
- fieldName: l_comment
  sourceName: /data/l_comment
  mappingStrategy: StringHashBSI
  type: String
  sourceOrdinal: 16

