tableName: cities
defaultPredicate: id > ''
primaryKey: id
attributes:
- sourceName: /id
  fieldName: id
  mappingStrategy: StringHashBSI
  type: String
- sourceName: /city
  fieldName: name
  mappingStrategy: StringHashBSI
  type: String
- sourceName: /state_name
  fieldName: state_name
  mappingStrategy: StringEnum
  type: String
- sourceName: /state_id
  fieldName: state
  mappingStrategy: StringEnum
  type: String
- sourceName: /county_name
  fieldName: county
  mappingStrategy: StringHashBSI
  type: String
- sourceName: /lat
  fieldName: latitude
  mappingStrategy: FloatScaleBSI
  type: Float
  scale: 4
- sourceName: /lng
  fieldName: longitude
  mappingStrategy: FloatScaleBSI
  type: Float
  scale: 4
- sourceName: /population
  fieldName: population
  mappingStrategy: IntBSI
  type: Integer
- sourceName: /density
  fieldName: density
  mappingStrategy: IntBSI
  type: Integer
- sourceName: /military
  fieldName: military
  mappingStrategy: BoolDirect
  type: Boolean
- sourceName: /timezone
  fieldName: timezone
  mappingStrategy: StringEnum
  type: String
- sourceName: /ranking
  fieldName: ranking
  mappingStrategy: IntBSI
  type: Integer
