tableName: customers_qa
primaryKey: cust_id
attributes:
- fieldName: cust_id
  sourceName: cust_id
  mappingStrategy: StringHashBSI
  type: String
- fieldName: first_name
  sourceName: first_name
  mappingStrategy: StringHashBSI
  type: String
- fieldName: last_name
  sourceName: last_name
  mappingStrategy: StringHashBSI
  type: String  
- fieldName: address
  sourceName: address
  mappingStrategy: StringHashBSI
  type: String
- fieldName: city
  sourceName: city
  mappingStrategy: StringEnum
  type: String
- fieldName: state
  sourceName: state
  mappingStrategy: StringHashBSI
  type: String
- fieldName: zip
  sourceName: zip
  mappingStrategy: StringHashBSI
  type: String
- fieldName: createdAtTimestamp
  mappingStrategy: SysMicroBSI
  defaultValue: now()
  type: DateTime
- fieldName: timestamp_micro
  mappingStrategy: SysMicroBSI
  type: DateTime
- fieldName: timestamp_millis
  mappingStrategy: SysMillisBSI
  type: DateTime  
- fieldName: hashedCustId
  mappingStrategy: StringHashBSI
  type: String
  defaultValue: tostring("not_hashed")
- fieldName: phone
  mappingStrategy: StringHashBSI
  type: String
- fieldName: phoneType
  mappingStrategy: StringEnum
  configuration:
    delim: ";"
  type: String
- fieldName: isActive
  mappingStrategy: BoolDirect
  defaultValue: 1
  type: Boolean
- fieldName: birthdate
  mappingStrategy: SysMicroBSI
  type: Date  
- fieldName: isLegalAge
  mappingStrategy: BoolDirect
  defaultValue: false
  type: Boolean
- fieldName: age
  mappingStrategy: IntBSI
  defaultValue: 0
  type: Integer
- fieldName: height
  mappingStrategy: FloatScaleBSI
  scale: 2
  type: Float
- fieldName: numFamilyMembers
  mappingStrategy: IntBSI
  defaultValue: 4
  type: Integer
- fieldName: rownum
  mappingStrategy: IntDirect
  type: Integer