tableName: cityzip
defaultPredicate: id > ''
primaryKey: zip+id
secondaryKeys: city+zip
attributes:
- sourceName: /zip
  fieldName: zip
  mappingStrategy: StringHashBSI
  type: String
- sourceName: /id
  fieldName: id
  mappingStrategy: StringHashBSI
  type: String
- sourceName: /name
  fieldName: city
  mappingStrategy: StringHashBSI
  type: String
- sourceName: /state
  fieldName: state
  mappingStrategy: StringEnum
  type: String
- sourceName: /id
  fieldName: city_id
  mappingStrategy: ParentRelation
  foreignKey: cities
  type: String
