tableName: nation
primaryKey: n_nationkey
selector: type="nation"
attributes:
- fieldName: n_nationkey
  sourceName: /data/n_nationkey
  mappingStrategy: IntBSI
  type: Integer
  sourceOrdinal: 1
  columnID: true
- fieldName: n_name
  sourceName: /data/n_name
  mappingStrategy: StringEnum
  type: String
  sourceOrdinal: 2
- fieldName: n_regionkey
  sourceName: /data/n_regionkey
  mappingStrategy: ParentRelation
  type: Integer
  foreignKey: region
  sourceOrdinal: 3
- fieldName: n_comment
  sourceName: /data/n_comment
  mappingStrategy: StringHashBSI
  type: String
  sourceOrdinal: 4
